version: '3.8'

networks:
  proxy:
    external: true
  agent_network:
    external: true

volumes:
  portainer_data: {}

configs:
  shepherd-docker-config:
    external: true

services:
  agent:
    image: portainer/agent:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer-ee:lts
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - proxy
    ports:
      - target: 9443
        published: 9443
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "com.crispsh.autodeploy=true"
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`console.${DOMAINNAME}`)"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
        - "traefik.http.services.portainer.loadbalancer.server.port=9443"
        - "traefik.http.services.portainer.loadbalancer.server.scheme=https"